### ISSUE TITLE
fail to load

### ISSUE THREAD

**Issue by joespinoza** [cibere/Flow.Launcher.Plugin.FlowLoadNotification#1]
fail to load
![Captura de pantalla 2024-11-27 123051](https://github.com/user-attachments/assets/8d0227cc-afec-48d4-9a60-5bb9351a312e)

**Comment by cibere** [comment]
> fail to load
> 
> ![Captura de pantalla 2024-11-27 123051](https://github.com/user-attachments/assets/8d0227cc-afec-48d4-9a60-5bb9351a312e)
> 
> 

hmm, can you send the flow launcher and flow.py log files?

for flow launcher's log file, use the log folder command with the system commands plugin and upload the file with the latest date 

for flow.py's log file, use the userdata folder command with the system commands plugin you open your userdata folder, head into the plugins directory, head into the FlowLoadNotification directory, and upload the log file (it should be named something like `flowpy.log`). If you can't find it, please be specific, ex: i found the FlowLoadNotification folder, but there was no log file inside

**Comment by joespinoza** [comment]
this one?
[2024-11-27.txt](https://github.com/user-attachments/files/17939969/2024-11-27.txt)

**Comment by cibere** [comment]
> this one?
> 
> [2024-11-27.txt](https://github.com/user-attachments/files/17939969/2024-11-27.txt)
> 
> 

Yeah. Did you find the flow.py log files aswell?

**Comment by joespinoza** [comment]
sorry, i found the FlowLoadNotification folder, but there was no log file inside with the name flowpy.log

**Comment by cibere** [comment]
Hmm alright. I'll dig into this in a little bit, but for now, I have one more question: Did you install the plugin through pluginmanager, or did you build it yourself?

**Comment by joespinoza** [comment]
pluginmanager

**Comment by cibere** [comment]
What version of flow launcher are you using? You can check by going to the `about` section of the settings menu

What version of python is flow using?
To check the python version, go to the `About` section in flow's settings, and scroll down till you see the `Python Path` field. Copy the path and send it here (the version is in the path)
![Visual Steps](https://github.com/user-attachments/assets/6bb39eed-d8ee-450c-9aec-5ccb881d0d5e)

**Comment by joespinoza** [comment]
C:\Users\Joe Espinoza\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe

**Comment by cibere** [comment]
> C:\Users\Joe Espinoza\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe

Can you try installing python 3.12 and telling flow to use that instead? FlowLoadNotification's backend uses features that were only introduced in 3.12, and so I assume the error is due to python 3.11 not knowing what to do.
Here is my recommendation for installing python 3.12:
1. Go to the [download site for 3.12.7](https://www.python.org/downloads/release/python-3127/), scroll down to the bottom, and find the installer thats best suited for you
![image](https://github.com/user-attachments/assets/67cbe18f-d2b4-46c8-a98f-05a1a3e13be2)
2. Click on custom installation
![image](https://github.com/user-attachments/assets/17b2207f-7981-49db-b22b-2869958ac6e4)
3. Uncheck `Documentation`, `tcl/tk and IDLE`, `Python test suite`, and optionally, `for all users`
![image](https://github.com/user-attachments/assets/c6735c9e-921a-4aff-a607-abb31e7683ce)
4. Make sure `pip` and `py launcher` are checked
![image](https://github.com/user-attachments/assets/b446d974-94d5-4be9-9a03-1e68346fb4b0)
5. On the advanced option screen, only check the things that you want (I don't think you need anything to be checked)
![image](https://github.com/user-attachments/assets/4fc110f1-1d86-4f73-bd7e-a2c122aa09d4)
6. Copy/write down the path python will be installed to
![image](https://github.com/user-attachments/assets/e30d77c9-690f-45b5-a1b7-313eefaa1614)
7. Press install and wait
8. Tell flow to use the new python installation by giving it the path from step #6 (add `/pythonw.exe` to the end of the path)
![image](https://github.com/user-attachments/assets/f2e6b961-aee9-4150-a03e-0ffc3d20ab11)

**Comment by joespinoza** [comment]
it's working, Thanks
